Add automation for bootstrapping an openQA developer box
rocky-linux/infrastructure pull request #14994
Opened 2021-08-30 01:55 UTC by akatch

This PR adds the playbook `init-rocky-openqa-developer-host.yml`, to be used for bootstrapping developer instances of OpenQA. This playbook mostly follows the automation from [this repo](https://github.com/rocky-linux/OpenQA-Fedora-Installation).

2021-08-30 01:57 UTC, nazunalika commented
Thank you for this PR! I will review it soon!

2021-08-30 15:47 UTC, nazunalika requested changes
I have looked through the playbook and tasks and noted where some things can be changed (either for simplification or consolidation). If you can possibly make these changes and the operations for setting up openqa work, I'll approve for merging.

2021-08-30 15:50 UTC, akatch commented
No problem, I won't be able to get to these changes until this evening
but I will gladly make them. Thanks for the feedback.

2021-08-31 00:15 UTC, nazunalika approved these changes

2021-08-31 00:17 UTC, nazunalika commented
Awesome, thank you for that! It looks good to me over all. I am assuming that it still builds and works with those changes. If they do, perfect, we'll get it merged in. Pinging @NeilHanlon to have a second look also.

2021-08-31 00:18 UTC, NeilHanlon approved these changes
Looks good! Thank you :)

2021-08-31 00:18 UTC, merged